const mongoose = require("mongoose");

const candidateSchema = new mongoose.Schema(
  {
    name: {
      type: String,
      required: true,
      trim: true,
    },

    email: {
      type: String,
      required: true,
      trim: true,
      lowercase: true,
    },

    phone: {
      type: String,
      default: "",
      trim: true,
    },

    resumeId: {
      type: mongoose.Schema.Types.ObjectId,
      ref: "Resume",
      default: null,
    },

    appliedJobId: {
      type: mongoose.Schema.Types.ObjectId,
      ref: "Job",
      required: true,
    },

    // Score generated by FastAPI
    resumeScore: {
      type: Number,
      default: null,
      min: 0,
      max: 100,
    },

    // Complete FastAPI screening response
    screeningResult: {
      type: mongoose.Schema.Types.Mixed,
      default: null,
    },

    matchedSkills: {
      type: [String],
      default: [],
    },

    missingSkills: {
      type: [String],
      default: [],
    },

    screeningStatus: {
      type: String,
      enum: [
        "pending",
        "shortlisted",
        "rejected",
      ],
      default: "pending",
    },

    /*
     * These fields are used later by Person 2.
     * Keeping them here makes the handoff easy.
     */
    testScore: {
      type: Number,
      default: null,
    },

    interviewScore: {
      type: Number,
      default: null,
    },

    finalScore: {
      type: Number,
      default: null,
    },
  },
  {
    timestamps: true,
  }
);

module.exports = mongoose.model(
  "Candidate",
  candidateSchema
);